spring:
  application:
    name: products-service
  datasource:
    url: jdbc:mysql://localhost:3306/products_db?serverTimezone=UTC
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka