spring:
  application:
    name: sales-service
  datasource:
    url: jdbc:mysql://localhost:3306/sales_db?serverTimezone=UTC
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
resilience4j:
  circuitbreaker:
    instances:
      salesService:
        register-health-indicator: true
        failure-rate-threshold: 50 
        minimum-number-of-calls: 10 
        sliding-window-size: 10 
        wait-duration-in-open-state: 10s 
        permitted-number-of-calls-in-half-open-state: 3 
        sliding-window-type: COUNT_BASED 
  retry:
    instances:
      shoppingCartService:
        max-attempts: 3 
        wait-duration: 1s